### ISSUE TITLE
Python2 issue

### ISSUE THREAD

**Issue by LinusU** [cocagne/pysrp#37]
Hello,

Just wanted you to know that on python2 `bytes(2)` returns the string `"2"`, whereas in python3 it returns `b"\x00\x00"`.

This makes the padding (inside `H()`) wrong in python2 which results in invalid values.

Discovered this while trying to make sure that pysrp and secure-remote-password are compatible (LinusU/secure-remote-password#13). Been ripping my hair out for the past few hours 😂

**Comment by cocagne** [comment]
Python2 support has been dropped. Thanks for the bug report.
