### ISSUE TITLE
telegram srp

### ISSUE THREAD

**Issue by iamDonkey** [cocagne/pysrp#49]
is it possible to implement telegram srp [https://core.telegram.org/api/srp](https://core.telegram.org/api/srp) using this library?

**Comment by cocagne** [comment]
The hashing, salting, math, and padding used in the telegram SRP protocol
differs significantly from RFC5054 which pysrp is based on. I don't think
you'd want to try and extend this library to simultaneously support both
protocols but you certainly could use pysrp as a guide for implementing a
new library tailored specifically to the telegram protocol. It'd take some
effort but from what I can see it should be fairly straightforward.

Tom
